### ISSUE TITLE
RequestParser type list + location json

### ISSUE THREAD

**Issue by d-ganchar** [flask-restful/flask-restful#739] opened 2018-02-21 09:57 UTC
The documentation says [Only use type=list when location='json'](http://flask-restful.readthedocs.io/en/0.3.5/reqparse.html#argument-locations). This is correct works in 0.3.5, but not in 0.3.6. 
How to check:

```
apilink_parser = reqparse.RequestParser()
apilink_parser.add_argument('foo', type=list, location='json')

@api.resource('/test')
class TestApi(Resource):

    def post(self):
        # example of client data: {"foo": ["test", "test2"]}
        args = apilink_parser.parse_args()
        # 0.3.5 parameter == <class 'list'>: ['test', 'test2']
        # 0.3.6 parameter == <class 'list'>: ['t', 'e', 's', 't']
        parameter = args.get('foo') 
```

Env:
Python: 2.7, 3+
Flask: 0.12.2

**Comment by joshfriend** [comment] 2018-02-21 22:24
Duplicate of #681

**Closed by joshfriend** 2018-02-21 22:24 UTC
