### ISSUE TITLE
Exception not being caught in 0.3.3

### ISSUE THREAD

**Issue by iamsteveholmes** [flask-restful/flask-restful#456] opened 2015-05-27 20:40 UTC
We have a inheritance tree of exceptions are subs of `Exception`.  Using 0.3.2, our tests are caught and returned as JSON.  With 0.3.3 the exception bubble up to the test runner causing a failure.  Here are examples of our Exceptions:
```python
class ApiException(Exception):
    def __init__(self, code, message):
        self.code = code
        if message is not None:
            self.data = {
                'status': code,
                'message': message
            }

class BadAuth(ApiException):
    def __init__(self,  message):
        self.code = 403
        if message is not None:
            self.data = {
                'status': self.code,
                'message': message
            }
```

**Comment by ueg1990** [comment] 2015-05-27 20:46
Hey, I may be wrong, but why can't you do this instead:

class BadAuth(ApiException):
    def __init__(self,  message):
        self.code = 403
        super(ApiException, self).__init__(self.code, message)

**Comment by joshfriend** [comment] 2015-05-27 21:12
@iamsteveholmes can you provide an example failing test case that demonstrates this?

**Comment by iamsteveholmes** [comment] 2015-05-27 21:16
@ueg1990 looks right.

**Comment by iamsteveholmes** [comment] 2015-05-27 21:18
@joshfriend our app is a bit nested for that and these are functional tests.  But let me see if I can come up with a simplified example.

**Comment by iamsteveholmes** [comment] 2015-05-27 21:55
[Here is an example](https://github.com/iamsteveholmes/flask-test)

**Comment by djcrabhat** [comment] 2015-05-28 02:40
Here's a script that works as expected with 0.3.2, but the exception bubbles all the way up on 0.3.3 
```
from flask import Flask
from flask_restful import Resource, Api

app = Flask(__name__)
api = Api(app)

class ApiError(Exception):
    def __init__(self, code, message = None):
        self.code = code
        if message is not None:
            self.data = {
                'status': code,
                'message': message
            }


class HelloWorld(Resource):
    def get(self):
        raise ApiError(404,'not found!')

api.add_resource(HelloWorld, '/')

if __name__ == '__main__':
    #app.run(debug=True)
    app.config['TESTING'] = True
    client = app.test_client()
    resp = client.get('/')
    print dict(data=resp.data, status=resp.status_code)
```

**Comment by justanr** [comment] 2015-05-28 14:05
Looks like the cause is the change from 0.3.2 and 0.3.3 in `handle_error`:

Relevant change:
```python
# in 0.3.2
if not hasattr(e, 'code') and current_app.propagate_exceptions:

# 0.3.3
if not isinstance(e, HTTPException) and current_app.propagate_exceptions
```

See #445, #111

**Comment by djcrabhat** [comment] 2015-05-28 15:43
Sublassing werkzeug.exceptions.HTTPException did the trick!  A real server no longer blows up the same way, and it works with app.testing = True.  Thanks so much for the explanation

**Comment by joshfriend** [comment] 2015-07-04 12:47
Closing since the change introduced by #342 was intended to work this way and it seems like everyone has found that subclassing `HTTPException` works perfectly well.

**Closed by joshfriend** 2015-07-04 12:47 UTC

**Comment by patrickyan** [comment] 2017-06-28 17:17
Docs should probably be updated to note that the error class needs to subclass HTTPException http://flask-restful.readthedocs.io/en/0.3.5/extending.html#define-custom-error-messages
