### ISSUE TITLE
Missing API section in documentation

### ISSUE THREAD

**Issue by RDCH106** [flask-restful/flask-restful#661] opened 2017-03-01 14:39 UTC
The documentation about the API section is missing:

![image](https://cloud.githubusercontent.com/assets/1483414/23464215/8c36eaae-fe94-11e6-94a0-b8204529777a.png)

http://flask-restful-cn.readthedocs.io/en/0.3.5/api.html

The documentation is still accessible from Google cache:

http://webcache.googleusercontent.com/search?q=cache:suP_SgbVOHAJ:flask-restful-cn.readthedocs.io/en/0.3.5/api.html+&cd=1&hl=es&ct=clnk&gl=es

**Comment by joshfriend** [comment] 2017-03-01 16:57
flask-restful-cn is a fork of this project: https://github.com/pretdo/Flask-RESTful-cn

I cannot help you with this and @pretdo has issues disabled on the fork.

**Comment by RDCH106** [comment] 2017-03-01 18:48
@joshfriend Sorry for the mistake!
The problem is present in this project too:

http://flask-restful.readthedocs.io/en/0.3.5/api.html

**Comment by joshfriend** [comment] 2017-03-01 19:44
Ah ok, you're right. Probably related to #660.

**Comment by EpocDotFr** [comment] 2017-03-12 09:46
The API section is still missing 😕

**Comment by yibinlin** [comment] 2017-07-02 01:07
Will this be resolved soon? It seems like the API doc and the latest docs are still broken. Thanks!

**Comment by Reshurum** [comment] 2017-07-07 17:08
I built the docs locally and cannot reproduce the problem. Could this be an issue with readthedocs?

**Comment by joshfriend** [comment] 2017-07-07 18:19
This is the RTD build log:

```
Running Sphinx v1.5.3
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/flask-restful/envs/0.3.6/lib/python3.5/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/flask-restful/envs/0.3.6/lib/python3.5/site-packages/sphinx/application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/flask-restful/envs/0.3.6/lib/python3.5/site-packages/sphinx/config.py", line 134, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/flask-restful/envs/0.3.6/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 129, in execfile_
    exec_(code, _globals)
  File "conf.py", line 54, in <module>
    from flask_restful.__version__ import __version__
ImportError: No module named 'flask_restful'

Exception occurred:
  File "conf.py", line 54, in <module>
    from flask_restful.__version__ import __version__
ImportError: No module named 'flask_restful'
The full traceback has been saved in /tmp/sphinx-err-kuycoynz.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by Reshurum** [comment] 2017-07-07 18:27
I got that error when I tried to build locally initially as well. I fixed it by setting my `PYTHONPATH` variable to include the project root. It also failed finding flask after I fixed that so I installed it in a virtual environment.

I have not deployed to RTD before so I don't know the best way to resolve this if this is the issue as I'm unfamiliar with the deployment process.

**Comment by bsandrow** [comment] 2017-07-20 15:05
Could this be fixed by changing [this](https://github.com/flask-restful/flask-restful/blob/master/docs/conf.py#L23):

```python
sys.path.append(os.path.abspath('../flask_restful'))
```

to this:

```python
sys.path.append(os.path.abspath('../'))
```

**Comment by oldani** [comment] 2017-08-23 17:24
When will it be solved? still nothing on docs :(

**Comment by RDCH106** [comment] 2017-08-24 08:55
The best option is using a web archive like [Wayback Machine](https://web.archive.org/web/20170102035912/http://flask-restful.readthedocs.io/en/0.3.5/api.html) to get the missing info and add it again in the current doc version.

@oldani use my link to access to the documentation.

**Comment by joshfriend** [comment] 2017-08-24 13:46
@bsandrow i tried that, no luck:

https://readthedocs.org/projects/flask-restful/builds/5878869/

**Comment by bsandrow** [comment] 2017-08-24 14:07
@joshfriend Well you moved from this:

```
Exception occurred:
  File "conf.py", line 54, in <module>
    from flask_restful.__version__ import __version__
ImportError: No module named 'flask_restful'
```
 to this:

```
Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/flask-restful/checkouts/latest/flask_restful/__init__.py", line 5, in <module>
    from flask import request, url_for, current_app
ImportError: cannot import name 'request'
```

So `flask_restful` was in the path, but `flask` might not be installed. I noticed that the `pip install` did _not_ include `flask`:

```
pip install --use-wheel -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/flask-restful/.cache/pip Pygments==2.2.0 setuptools==28.8.0 docutils==0.13.1 mock==1.0.1 pillow==2.6.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.4.0 sphinx==1.5.3 sphinx-rtd-theme<0.3 readthedocs-sphinx-ext<0.6
```

Maybe try adding `flask` to the doc requirements?

**Comment by bsandrow** [comment] 2017-08-24 14:43
Checkout PR #698 for another possible fix (without messing around with `sys.path`).

**Closed** 2017-08-24 14:56 UTC
Labels: docs
