### ISSUE TITLE
BUG coding problem 

### ISSUE THREAD

**Issue by wysfl** [flask-restful/flask-restful#629] opened 2016-09-29 08:17 UTC
```python
# -*- coding: utf-8 -*-
from flask import Flask
from flask_restful import Resource, Api
app = Flask(__name__)
api = Api(app)

app.config["RESTFUL_JSON"] = {'ensure_ascii':False}

class HelloWorld(Resource):
    def  get(self):
        return {'msg': u'你好世界！'}

api.add_resource(HelloWorld, '/')

if __name__ == '__main__':
    app.run(debug=True)


# result:
# {
#     "msg": "浣犲ソ涓栫晫锛�"
# }



# -*- coding: utf-8 -*-
from flask import Flask
from json import dumps
app = Flask(__name__)

@app.route('/')
def hello_world():

    return dumps({'msg': '你好世界！'},ensure_ascii=False)

if __name__ == '__main__':
    app.run()



# result:
#{"msg": "你好世界！"}


This is what I want to be the result

 {
     "msg": "你好世界！"
 }

```

**Comment by joshfriend** [comment] 2016-09-29 12:29
Duplicate of #591

Please discuss there instead of opening new issues for the exact same question.

**Closed by joshfriend** 2016-09-29 12:29 UTC
Labels: duplicate
