### ISSUE TITLE
Access-Control-Allow-Origin not attached when status code is not 200

### ISSUE THREAD

**Issue by Evlos** [flask-restful/flask-restful#588] opened 2016-05-18 06:43 UTC
```
api.decorators = [flask_restful.utils.cors.crossdomain(
    origin='*',
    methods=['get', 'post', 'put', 'patch', 'options'],
    headers=['content-type']
)]
```

I am using the build-in cors support, but Access-Control-Allow-Origin won't be attached in headers when status code is not 200.

Please check this out, thanks!

**Comment by joshfriend** [comment] 2016-05-18 23:12
duplicate of #229

**Closed by joshfriend** 2016-05-18 23:12 UTC
