### ISSUE TITLE
Documentation on readthedocs is down

### ISSUE THREAD

**Issue by skavie** [flask-restful/flask-restful#660] opened 2017-02-28 00:47 UTC
http://flask-restful.readthedocs.io returns a 404!

**Comment by afilbert** [comment] 2017-02-28 03:40
Second. What's up with the docs? Looks like I can still pull down on my laptop from cache, but my desktop doesn't resolve because I've never accessed it before.

**Comment by danlindow** [comment] 2017-02-28 05:21
For the time being you can use google cached pages. Example:
https://webcache.googleusercontent.com/search?q=cache:r6v5zHPlrs8J:flask-restful-cn.readthedocs.io/en/0.3.5/+&cd=1&hl=en&ct=clnk&gl=us

**Comment by joshfriend** [comment] 2017-02-28 06:40
Thanks for the reports, I'm looking into it.

**Comment by cank** [comment] 2017-02-28 18:11
One can look at a fairly useable version of the documents directly on github:

https://github.com/flask-restful/flask-restful/tree/master/docs

**Comment by joshfriend** [comment] 2017-02-28 18:53
Everything should be back to normal now.

It appears that the project was deleted from RTD, which allowed someone else to recreate it. RTD just transferred ownership of the project back to me a few minutes ago and I re-deployed the last 3 tags and the "latest" version. Those should be available now, or within a few minutes.

RTD thinks this may have been an accidental deletion caused by a bug which cascaded deletion of a docs translation to the parent project itself. I did a quick search of their issues list and [found this PR, which appears to be related to the bug in question](https://github.com/rtfd/readthedocs.org/pull/2574).

I'm fairly certain there was nothing malicious happening, but I've also rotated my RTD account passwords just in case.

Sorry for the inconvenience. If anyone finds lingering issues, please post here and I'll look into it.

**Closed by joshfriend** 2017-02-28 18:53 UTC
Labels: docs
