### ISSUE TITLE
Allow HTTPExceptions to specify headers

### ISSUE THREAD

**Issue by heston** [flask-restful/flask-restful#455] opened 2015-05-27 17:53 UTC
Currently, an `HTTPException` raised from a Flask-Restful handler does not propagate custom headers. This is because `handle_error` creates a new response from the exception, ignoring headers.

Werkzeug's [HTTPException](https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/exceptions.py#L75) classes can generate their own responses, including headers. Flask-Restful overrides this behavior to provide a response of the proper type (e.g. JSON instead of HTML). In so doing, it copies the status code and data attributes from the original exception, but it ignores any headers that may be present.

This PR adds simple support to propagate headers from an exception to the eventual response: https://github.com/flask-restful/flask-restful/pull/450

**Comment by joshfriend** [comment] 2015-06-05 05:45
I'm closing this as a duplicate of #450 since you already created a PR and it would be more appropriate to discuss details there.

**Closed by joshfriend** 2015-06-05 05:45 UTC
