### ISSUE TITLE
Wrong format of parameter got, when I using the list(string) as RequestParser

### ISSUE THREAD

**Issue by thinksource** [flask-restful/flask-restful#738] opened 2018-02-19 17:55 UTC
I use the last version of flask-restful:
My code like:

```
from flask_restful import Resource, reqparse

apilink_parser = reqparse.RequestParser()
apilink_parser.add_argument('provider_id', type=int,required=True)
apilink_parser.add_argument('name', type=str, required=True)
apilink_parser.add_argument('func_id', type=int)
apilink_parser.add_argument('method', type=str)
apilink_parser.add_argument('url', type=str)
apilink_parser.add_argument('parameter',type=list, location='json')
apilink_parser.add_argument("expectreturn", type=list)


@marshal_with(apilink_fields)
def post(self):
    args = apilink_parser.parse_args()
    print(args)  ####here I print the args
    # user owns the task
    task = APILink.create(**args)
    return task, 201
```

My json post data like:

```
{ 
"name":"riskiqwhois",
"provider_id":1,
"func_id":1,
"url":"myurl",
"parameter":["query"],  //******//
"expectreturn":[],
"method":"post"
 }
```

But the args in #### I print is :

```
 {
 'provider_id': 1, 
 'name': 'riskiqwhois', 
 'func_id': 1, 
 'method': 'post', 
 'url': 'myurl', 
 'parameter': ['q', 'u', 'e', 'r', 'y'], //******//
 'expectreturn': None
  }
```

Why the star line is different, How to make it the list(string) if I only give one element of the list instead of list(char) value as the parameter?

**Comment by joshfriend** [comment] 2018-02-19 18:37
Duplicate of #681

**Closed by joshfriend** 2018-02-19 18:37 UTC
